import {type Event} from '@/entities/Event'

export const mockEvents: Event[] = [
	{
		id: '1',
		name: 'React Summit 2024',
		description: 'Крупнейшая конференция по React в России. Доклады от ведущих разработчиков, практические мастер-классы и нетворкинг.',
		image: 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'160\'%3E%3Crect fill=\'%234F46E5\' width=\'400\' height=\'160\'/%3E%3Ctext fill=\'%23FFFFFF\' font-family=\'Arial\' font-size=\'20\' x=\'50%25\' y=\'50%25\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3EReact Summit%3C/text%3E%3C/svg%3E',
		date: '15-17 марта 2024',
		location: 'Москва, Крокус Экспо',
		type: 'conference',
		attendees: 1200,
		isUpcoming: true,
	},
	{
		id: '2',
		name: 'Frontend Meetup #42',
		description: 'Ежемесячная встреча фронтенд-разработчиков. Обсуждение новых технологий, обмен опытом и живое общение.',
		image: 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'160\'%3E%3Crect fill=\'%2310B981\' width=\'400\' height=\'160\'/%3E%3Ctext fill=\'%23FFFFFF\' font-family=\'Arial\' font-size=\'18\' x=\'50%25\' y=\'50%25\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3EFrontend Meetup%3C/text%3E%3C/svg%3E',
		date: '28 февраля 2024',
		location: 'Санкт-Петербург, IT-парк',
		type: 'meetup',
		attendees: 150,
	},
	{
		id: '3',
		name: 'TypeScript Deep Dive',
		description: 'Продвинутый курс по TypeScript от эксперта. Изучение сложных концепций, паттернов и лучших практик.',
		image: 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'160\'%3E%3Crect fill=\'%233B82F6\' width=\'400\' height=\'160\'/%3E%3Ctext fill=\'%23FFFFFF\' font-family=\'Arial\' font-size=\'20\' x=\'50%25\' y=\'50%25\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3ETypeScript%3C/text%3E%3C/svg%3E',
		date: '10 марта 2024',
		location: 'Онлайн',
		type: 'lecture',
		attendees: 300,
	},
	{
		id: '4',
		name: 'DevOps Days 2024',
		description: 'Конференция по DevOps и автоматизации. Практические кейсы, инструменты и методологии современной разработки.',
		image: 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'160\'%3E%3Crect fill=\'%23F59E0B\' width=\'400\' height=\'160\'/%3E%3Ctext fill=\'%23FFFFFF\' font-family=\'Arial\' font-size=\'20\' x=\'50%25\' y=\'50%25\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3EDevOps Days%3C/text%3E%3C/svg%3E',
		date: '5-6 апреля 2024',
		location: 'Казань, Центр современной культуры',
		type: 'conference',
		attendees: 800,
	},
	{
		id: '5',
		name: 'Mobile Development Workshop',
		description: 'Интенсивный воркшоп по мобильной разработке. Создание приложений с нуля до публикации в App Store.',
		image: 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'160\'%3E%3Crect fill=\'%238B5CF6\' width=\'400\' height=\'160\'/%3E%3Ctext fill=\'%23FFFFFF\' font-family=\'Arial\' font-size=\'20\' x=\'50%25\' y=\'50%25\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3EMobile Dev%3C/text%3E%3C/svg%3E',
		date: '20 марта 2024',
		location: 'Екатеринбург, УрФУ',
		type: 'lecture',
		attendees: 200,
	},
	{
		id: '6',
		name: 'AI & ML Conference',
		description: 'Конференция по искусственному интеллекту и машинному обучению. Последние достижения и практические применения.',
		image: 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'160\'%3E%3Crect fill=\'%23EC4899\' width=\'400\' height=\'160\'/%3E%3Ctext fill=\'%23FFFFFF\' font-family=\'Arial\' font-size=\'20\' x=\'50%25\' y=\'50%25\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3EAI %26amp%3B ML%3C/text%3E%3C/svg%3E',
		date: '12-14 мая 2024',
		location: 'Новосибирск, Технопарк',
		type: 'conference',
		attendees: 950,
	},
]
